apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: k5pufyeix-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k5pufyeix-python 
  name: k5pufyeix-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: k5pufyeix-python 
